- name: variables at task level
  hosts: localhost
  - money: "10000 rs"
    land: "100 hectars"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
     msg: "money: {{money}}, land{{land}}"
  - name: inherit values from play and add and override
    vars:
    - money: "20000rs"
      houses: "3 houses"
    ansible.builtin.debug:
     msg: "money: {{money}}, land{{land}}, houses{{houses}}"
    