- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: Sivakumar-play
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: Please enter Trainer Name
    private: false
  tasks:
  - name: variable at task level
    ansible.builtin.debug:
      msg: "Trainer name is: {{NAME}}"